# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-RiTTBxam0rWPphL2MgjBUlsI1mClfuU

|-------------------|---------------------|-------------------|----------------|
|Program            |Software manufacturer|Software version   |Software type   |
|Windows10          |Bill Gates           |22H2               |Operation system|
|Steam              |Valve                |API v020           |Game store      |
|Chrome             |Google               |106.0.5249.112     |Browser         |
|Discord            |Hammer&Chisel        |2.7.8              |social platform |
|-------------------|---------------------|-------------------|----------------|

|-------------------|---------------------|-------------------|----------------|
|App                |Software manufacturer|Software version   |Software type   |
|Instagram          |Facebook             |255.1.0.17.102     |Social media    |
|Whatsapp           |Jan Koum&Brain Action|2.22.22.8          |Social media    |
|Twitter            |Parag Agrawal        |11.7.1             |Social media    |
|Netflix            |Marc Randolph        |4.16.1             |Entertainment   |
|-------------------|---------------------|-------------------|----------------|
"""